plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'expo.modules.inneraudio'
version = '0.1.0'
android {
  namespace 'expo.modules.inneraudio'
  defaultConfig { versionCode 1; versionName '0.1.0' }
}

dependencies {
  implementation 'androidx.media:media:1.7.0'
  implementation 'androidx.core:core-ktx:1.12.0'
}
