// plugins/withNoFontWeightAdjustment.js
//
// Android 12+ lets users turn on "Bold text" (Configuration.fontWeightAdjustment). TextViews apply
// that adjustment when they draw, but React Native measures text with the app's own typeface
// WITHOUT it. Result: any text that shrink-wraps to its measured width (chips, pills, tags)
// is drawn slightly wider than the box it was given and its last glyph is clipped
// ("Water" -> "Wate", "Glossary" -> "Glossar").
//
// Fix: give the Activity a configuration with the weight adjustment neutralised, so drawing and
// measuring agree. Inner ships static custom fonts (CalSans / Inter) with deliberately chosen
// weights, so ignoring the system weight bump here is consistent with the design; font SCALE
// (the separate "Font size" setting) is untouched and still respected.
//
// android/ is gitignored and regenerated by `expo prebuild`; this plugin makes the change durable.
const { withMainActivity } = require('@expo/config-plugins');

const MARKER = 'withNoFontWeightAdjustment';

const IMPORTS = [
  'import android.content.Context',
  'import android.content.res.Configuration',
];

const METHOD = `
  // ${MARKER}: keep React Native's text measurement and Android's drawing in agreement when the
  // system "Bold text" setting is on (otherwise shrink-wrapped labels lose their last letter).
  override fun attachBaseContext(newBase: Context) {
    var base = newBase
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      val config = Configuration(newBase.resources.configuration)
      if (config.fontWeightAdjustment != 0 &&
          config.fontWeightAdjustment != Configuration.FONT_WEIGHT_ADJUSTMENT_UNDEFINED) {
        config.fontWeightAdjustment = 0
        base = newBase.createConfigurationContext(config)
      }
    }
    super.attachBaseContext(base)
  }
`;

module.exports = function withNoFontWeightAdjustment(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error('withNoFontWeightAdjustment only supports a Kotlin MainActivity');
    }
    let src = cfg.modResults.contents;
    if (src.includes(MARKER)) return cfg; // already applied

    for (const line of IMPORTS) {
      if (!src.includes(line)) {
        src = src.replace('import android.os.Build', `${line}\nimport android.os.Build`);
      }
    }

    const anchor = 'class MainActivity : ReactActivity() {';
    if (!src.includes(anchor)) {
      throw new Error(`withNoFontWeightAdjustment: could not find "${anchor}" in MainActivity`);
    }
    src = src.replace(anchor, anchor + '\n' + METHOD);
    cfg.modResults.contents = src;
    return cfg;
  });
};
