// plugins/withProceduralDevFlavor.js
//
// android/ is gitignored and regenerated by `expo prebuild` (see CLAUDE.md: never hand-edit
// it and expect the change to stick). To make the "Inner Lab" dev build durable across
// prebuilds, this plugin injects a Gradle product flavor into android/app/build.gradle:
//   - prod          -> applicationId com.getinner.app            (unchanged production identity)
//   - proceduralDev -> applicationId com.getinner.app.proceduraldev, app name "Inner Lab"
// This lets the procedural-audio dev build install side by side with production from a
// single prebuilt android/ project, e.g. `./gradlew :app:installProceduralDevDebug`.
//
// EAS build profiles pin `android.gradleCommand` to the "prod" flavor in eas.json, so
// existing production/preview/internal builds are unaffected by the added flavor dimension.
const { withAndroidManifest, withAppBuildGradle } = require('@expo/config-plugins');

const ANCHOR = "namespace 'com.getinner.app'";

const FLAVOR_BLOCK = `
    // Injected by plugins/withProceduralDevFlavor.js — edit the plugin, not this file;
    // android/ is regenerated by \`expo prebuild\` and any direct edit here will be lost.
    flavorDimensions "target"
    productFlavors {
        prod {
            dimension "target"
            applicationId "com.getinner.app"
            manifestPlaceholders = [innerAppScheme: "exp+inner"]
            buildConfigField "boolean", "INNER_PROCEDURAL_DEV_BUILD", "false"
        }
        proceduralDev {
            dimension "target"
            applicationId "com.getinner.app.proceduraldev"
            manifestPlaceholders = [innerAppScheme: "inner-procedural-dev"]
            resValue "string", "app_name", "Inner Lab"
            buildConfigField "boolean", "INNER_PROCEDURAL_DEV_BUILD", "true"
        }
    }
`;

function withProceduralDevFlavor(config) {
  config = withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withProceduralDevFlavor only supports the Groovy android/app/build.gradle');
    }
    const contents = cfg.modResults.contents;
    if (contents.includes('flavorDimensions "target"')) {
      return cfg; // already applied
    }
    if (!contents.includes(ANCHOR)) {
      throw new Error(
        `withProceduralDevFlavor: could not find '${ANCHOR}' in android/app/build.gradle to anchor on.`
      );
    }
    cfg.modResults.contents = contents.replace(ANCHOR, ANCHOR + '\n' + FLAVOR_BLOCK);
    return cfg;
  });
  return withAndroidManifest(config, (cfg) => {
    const activities = cfg.modResults.manifest.application?.[0]?.activity ?? [];
    for (const activity of activities) {
      for (const filter of activity['intent-filter'] ?? []) {
        for (const data of filter.data ?? []) {
          const scheme = data.$?.['android:scheme'];
          if (scheme === 'exp+inner' || scheme === 'inner-procedural-dev') {
            data.$['android:scheme'] = '${innerAppScheme}';
          }
        }
      }
    }
    return cfg;
  });
}

module.exports = withProceduralDevFlavor;
