package expo.modules.inneraudio

import org.json.JSONArray
import org.json.JSONObject
import org.junit.After
import org.junit.Assert.*
import org.junit.Test
import kotlin.math.abs
import kotlin.math.sqrt

/**
 * First full-length production Overnight Journey run through the real
 * ProceduralAudioEngine, driven offline (no AudioTrack/service/hardware).
 * The authored timeline is loaded verbatim from a fixture generated by the
 * actual production TypeScript builder (core/audio/overnightJourney.ts +
 * overnightProtocol.ts + timeline.ts), NOT reconstructed by hand -- see
 * `overnight-full-night-fixture.json` and the generating script recorded in
 * the accompanying report. This is an Android-native-engine characterization
 * run: it says nothing about iOS, foreground-service survival, AudioTrack,
 * routes, Bluetooth, wake locks, or real-device background execution.
 */
class OvernightFullNightTest {

  @After fun cleanup() {
    ProceduralAudioEngine.wallClockMs = { System.currentTimeMillis() }
    ProceduralAudioEngine.onSleepTimerElapsed = null
    ProceduralAudioEngine.checkpointSessionId = null
    ProceduralAudioEngine.reset()
  }

  private fun loadFixture(fileName: String): JSONObject {
    val stream = javaClass.classLoader!!.getResourceAsStream(fileName)
      ?: error("$fileName not found on test classpath")
    return JSONObject(stream.bufferedReader().readText())
  }

  private fun configFrom(json: JSONObject): AudioConfigRecord = AudioConfigRecord().apply {
    carrierHz = json.getDouble("carrierHz")
    binauralCarrierHz = json.getDouble("binauralCarrierHz")
    binauralDeltaHz = json.getDouble("binauralDeltaHz")
    toneGain = json.getDouble("toneGain")
    harmonicWarmth = json.getDouble("harmonicWarmth")
    binauralGain = json.getDouble("binauralGain")
    noiseColor = if (json.isNull("noiseColor")) null else json.getString("noiseColor")
    noiseGain = json.getDouble("noiseGain")
    environment = json.getString("environment")
    environmentGain = json.getDouble("environmentGain")
    environmentIntensity = json.getDouble("environmentIntensity")
    thresholdShift = json.getDouble("thresholdShift")
    identityPresence = json.getDouble("identityPresence")
    identityDensity = json.getDouble("identityDensity")
    identityVariety = json.getDouble("identityVariety")
    noiseHighCutHz = json.getDouble("noiseHighCutHz")
    noiseWidth = json.getDouble("noiseWidth")
    noiseDriftDb = json.getDouble("noiseDriftDb")
    noiseDriftSeconds = json.getDouble("noiseDriftSeconds")
    binauralBreathDb = json.getDouble("binauralBreathDb")
    binauralBreathInSeconds = json.getDouble("binauralBreathInSeconds")
    binauralBreathOutSeconds = json.getDouble("binauralBreathOutSeconds")
    binauralBreathVariation = json.getDouble("binauralBreathVariation")
    harmonicTranslation = json.getDouble("harmonicTranslation")
    templeGain = json.getDouble("templeGain")
    templeIntensity = json.getDouble("templeIntensity")
    masterGain = json.getDouble("masterGain")
    rampMs = json.getDouble("rampMs")
    spatialMode = json.getString("spatialMode")
    spatialTarget = json.getString("spatialTarget")
    spatialDepth = json.getDouble("spatialDepth")
    spatialRate = json.getDouble("spatialRate")
  }

  private fun timelineFrom(fixture: JSONObject): AudioTimelineRecord = AudioTimelineRecord().apply {
    id = "overnight-full-night"
    title = fixture.getString("title")
    seed = fixture.getDouble("seed")
    val stagesJson: JSONArray = fixture.getJSONArray("stages")
    stages = (0 until stagesJson.length()).map { i ->
      val stageJson = stagesJson.getJSONObject(i)
      TimelineStageRecord().apply {
        id = stageJson.getString("id")
        label = stageJson.getString("label")
        durationMs = stageJson.getDouble("durationMs")
        transitionMs = stageJson.getDouble("transitionMs")
        config = configFrom(stageJson.getJSONObject("config"))
        val eventsJson = stageJson.getJSONArray("spatialEvents")
        spatialEvents = (0 until eventsJson.length()).map { j ->
          val e = eventsJson.getJSONObject(j)
          SpatialEventRecord().apply {
            id = e.getString("id")
            atMs = e.getDouble("atMs")
            type = e.getString("type")
            recognitionSpace = e.optBoolean("recognitionSpace", false)
          }
        }
      }
    }
  }

  data class Window(
    val startMs: Double,
    var sumSquares: Double = 0.0,
    var sampleCount: Long = 0,
    var peakAbs: Float = 0f,
    var nonFiniteCount: Long = 0,
  ) {
    fun rms() = if (sampleCount > 0) sqrt(sumSquares / sampleCount) else 0.0
  }

  @Test fun fullProductionOvernightJourneyRunsToCompletion() {
    runFullNightScenario(
      fixtureFileName = "overnight-full-night-fixture.json",
      tag = "full-night",
      checkpointSessionId = "full-night",
    )
  }

  /**
   * Second production configuration: Forest environment, Deep feel, Chimes
   * recognition signal, 8h sleep duration, seed 42424242 (distinct from the
   * Ocean/Gentle/Droplets run above). Same fixture-from-real-builder
   * provenance as the first run -- see the accompanying report for the
   * generating script. Validates the same invariants plus per-hour
   * throughput/heap checkpoints added to the shared harness below.
   */
  @Test fun forestDeepChimesOvernightJourneyRunsToCompletion() {
    runFullNightScenario(
      fixtureFileName = "overnight-forest-deep-chimes-fixture.json",
      tag = "forest-night",
      checkpointSessionId = "forest-night",
    )
  }

  /** Temple / Immersive / Bell / 8h, seed 31415926. Part of the four-environment sweep. */
  @Test fun templeImmersiveBellOvernightJourneyRunsToCompletion() {
    runFullNightScenario(
      fixtureFileName = "overnight-temple-immersive-bell-fixture.json",
      tag = "temple-night",
      checkpointSessionId = "temple-night",
    )
  }

  /** Cosmic / Gentle / Ascending / 8h, seed 27182818. Part of the four-environment sweep. */
  @Test fun cosmicGentleAscendingOvernightJourneyRunsToCompletion() {
    runFullNightScenario(
      fixtureFileName = "overnight-cosmic-gentle-ascending-fixture.json",
      tag = "cosmic-night",
      checkpointSessionId = "cosmic-night",
    )
  }

  /** Fire / Deep / Droplets / 8h, seed 16180339. Part of the four-environment sweep. */
  @Test fun fireDeepDropletsOvernightJourneyRunsToCompletion() {
    runFullNightScenario(
      fixtureFileName = "overnight-fire-deep-droplets-fixture.json",
      tag = "fire-night",
      checkpointSessionId = "fire-night",
    )
  }

  /** Abyssal / Immersive / Chimes / 8h, seed 14142135. Part of the four-environment sweep. */
  @Test fun abyssalImmersiveChimesOvernightJourneyRunsToCompletion() {
    runFullNightScenario(
      fixtureFileName = "overnight-abyssal-immersive-chimes-fixture.json",
      tag = "abyssal-night",
      checkpointSessionId = "abyssal-night",
    )
  }

  private fun runFullNightScenario(fixtureFileName: String, tag: String, checkpointSessionId: String) {
    val fixture = loadFixture(fixtureFileName)
    val timeline = timelineFrom(fixture)
    val baseConfig = AudioConfigRecord()
    val expectedTotalDurationMs = fixture.getDouble("totalDurationMs")
    val bufferFrames = 960 // production RENDER_CHUNK_FRAMES (InnerAudioPlaybackService.kt)
    val windowMs = 300_000.0 // 5-minute audio-health windows, bounded memory

    ProceduralAudioEngine.reset()
    ProceduralAudioEngine.onSleepTimerElapsed = null
    ProceduralAudioEngine.checkpointSessionId = null
    val sampleRate = ProceduralAudioEngine.sampleRate
    var cumulativeFrames = 0L
    val baseWallMs = 0L
    ProceduralAudioEngine.wallClockMs = { baseWallMs + (cumulativeFrames * 1_000.0 / sampleRate).toLong() }

    ProceduralAudioEngine.configure(baseConfig)
    ProceduralAudioEngine.setTimeline(timeline)
    ProceduralAudioEngine.checkpointSessionId = checkpointSessionId
    ProceduralAudioEngine.setSleepTimer(baseWallMs + expectedTotalDurationMs)

    var completionCount = 0
    var completionCumulativeFrames: Long? = null
    var completionProtocolPositionMs: Double? = null
    ProceduralAudioEngine.onSleepTimerElapsed = {
      completionCount++
      completionCumulativeFrames = cumulativeFrames
      completionProtocolPositionMs = ProceduralAudioEngine.getTimelinePositionMs()
    }

    val stageTransitions = mutableListOf<Pair<String, Double>>()
    val cueFires = mutableListOf<Map<String, Any?>>()
    var lastStageId: String? = null
    var nonFiniteTotal = 0L
    var peakAbsTotal = 0f
    var sumSquaresTotal = 0.0
    var totalSamples = 0L
    val windows = mutableListOf<Window>()
    var currentWindow = Window(0.0)
    var runtimeExceptionCaught: Throwable? = null

    val jvmMemoryBefore = run {
      System.gc()
      val rt = Runtime.getRuntime()
      rt.totalMemory() - rt.freeMemory()
    }
    var peakJvmMemory = jvmMemoryBefore

    val buffer = FloatArray(bufferFrames * 2)
    var buffersAfterCompletion = 0
    var iterations = 0L
    val startedAtNanos = System.nanoTime()
    var lastProgressLogFrames = 0L
    val totalFramesExpected = (expectedTotalDurationMs * sampleRate / 1_000.0).toLong()

    data class HourCheckpoint(
      val hourIndex: Int,
      val simulatedMsCumulative: Double,
      val hourWallMs: Double,
      val realtimeMultiple: Double,
      val heapUsedBytes: Long,
    )
    val hourCheckpoints = mutableListOf<HourCheckpoint>()
    var lastHourCheckpointNanos = startedAtNanos
    var lastHourCheckpointFrames = 0L

    try {
      while (true) {
        iterations++
        java.util.Arrays.fill(buffer, 0f)
        ProceduralAudioEngine.render(buffer, bufferFrames)
        cumulativeFrames += bufferFrames
        val positionMs = cumulativeFrames * 1_000.0 / sampleRate

        for (i in 0 until bufferFrames * 2) {
          val sample = buffer[i]
          if (sample.isNaN() || sample.isInfinite()) {
            nonFiniteTotal++
            currentWindow.nonFiniteCount++
          }
          val magnitude = abs(sample)
          if (magnitude > peakAbsTotal) peakAbsTotal = magnitude
          if (magnitude > currentWindow.peakAbs) currentWindow.peakAbs = magnitude
          val sq = sample.toDouble() * sample.toDouble()
          sumSquaresTotal += sq
          currentWindow.sumSquares += sq
          totalSamples++
          currentWindow.sampleCount++
        }

        if (positionMs - currentWindow.startMs >= windowMs) {
          windows.add(currentWindow)
          currentWindow = Window(positionMs)
        }

        // Stage-transition polling throttled to ~1/sec (every 50 buffers at
        // 960 frames/48kHz) -- ample resolution given the shortest stage is
        // 60 real seconds; avoids 1.4M redundant checkpointSnapshot() calls.
        if (iterations % 50 == 0L || iterations == 1L) {
          val stageId = ProceduralAudioEngine.checkpointSnapshot()?.get("stageId") as? String
          if (stageId != null && stageId != lastStageId) {
            stageTransitions.add(stageId to positionMs)
            lastStageId = stageId
          }
        }

        for (event in ProceduralAudioEngine.drainDiagnosticEvents()) {
          if (event["type"] == "recognition_signal_fired") cueFires.add(event)
        }

        if (iterations % 5_000 == 0L) {
          val rt = Runtime.getRuntime()
          val used = rt.totalMemory() - rt.freeMemory()
          if (used > peakJvmMemory) peakJvmMemory = used
        }
        if (cumulativeFrames - lastProgressLogFrames >= sampleRate.toLong() * 3600) {
          lastProgressLogFrames = cumulativeFrames
          println("[$tag] progress: simulatedMs=${positionMs.toLong()} of ${expectedTotalDurationMs.toLong()}")

          val nowNanos = System.nanoTime()
          val hourWallMs = (nowNanos - lastHourCheckpointNanos) / 1_000_000.0
          val framesThisHour = cumulativeFrames - lastHourCheckpointFrames
          val simulatedMsThisHour = framesThisHour * 1_000.0 / sampleRate
          val heapUsed = run {
            val rt = Runtime.getRuntime()
            rt.totalMemory() - rt.freeMemory()
          }
          hourCheckpoints.add(
            HourCheckpoint(
              hourIndex = hourCheckpoints.size + 1,
              simulatedMsCumulative = positionMs,
              hourWallMs = hourWallMs,
              realtimeMultiple = simulatedMsThisHour / hourWallMs,
              heapUsedBytes = heapUsed,
            ),
          )
          lastHourCheckpointNanos = nowNanos
          lastHourCheckpointFrames = cumulativeFrames
        }

        if (completionCount > 0) {
          buffersAfterCompletion++
          if (buffersAfterCompletion > 5) break
        }
        // Safety bound: stop well past the expected end even if completion
        // logic somehow never fires, so a real failure doesn't spin forever.
        if (cumulativeFrames > totalFramesExpected + sampleRate.toLong() * 120) break
      }
    } catch (t: Throwable) {
      runtimeExceptionCaught = t
      println(
        "[$tag] FAILURE at simulatedMs=${cumulativeFrames * 1_000.0 / sampleRate} " +
          "cumulativeFrames=$cumulativeFrames activeStage=$lastStageId lastCue=${cueFires.lastOrNull()?.get("cueId")}",
      )
    }
    if (currentWindow.sampleCount > 0) windows.add(currentWindow)

    val elapsedMs = (System.nanoTime() - startedAtNanos) / 1_000_000.0
    val rtMemAfter = run {
      val rt = Runtime.getRuntime()
      rt.totalMemory() - rt.freeMemory()
    }

    println("[$tag] ===== RESULT =====")
    println("[$tag] failure=${runtimeExceptionCaught}")
    println("[$tag] totalRenderedFrames=$cumulativeFrames simulatedMs=${cumulativeFrames * 1_000.0 / sampleRate}")
    println("[$tag] executionWallMs=$elapsedMs realtimeMultiple=${(cumulativeFrames * 1_000.0 / sampleRate) / elapsedMs}")
    println("[$tag] stageTransitions=${stageTransitions.size}")
    stageTransitions.forEach { println("[$tag]   stage=${it.first} atMs=${it.second}") }
    println("[$tag] cueFires=${cueFires.size}")
    cueFires.forEach {
      println(
        "[$tag]   cue=${it["cueId"]} scheduled=${it["scheduledPositionMs"]} " +
          "actual=${it["actualPositionMs"]} drift=${it["driftMs"]}",
      )
    }
    println("[$tag] completionCount=$completionCount completionCumulativeFrames=$completionCumulativeFrames completionProtocolPositionMs=$completionProtocolPositionMs")
    println("[$tag] nonFiniteTotal=$nonFiniteTotal peakAbsTotal=$peakAbsTotal globalRms=${sqrt(sumSquaresTotal / totalSamples)}")
    println("[$tag] jvmMemoryBeforeBytes=$jvmMemoryBefore peakJvmMemoryBytes=$peakJvmMemory jvmMemoryAfterBytes=$rtMemAfter")
    println("[$tag] hourCheckpoints=${hourCheckpoints.size}")
    hourCheckpoints.forEach {
      println(
        "[$tag]   hour=${it.hourIndex} simulatedMsCumulative=${it.simulatedMsCumulative} " +
          "hourWallMs=${it.hourWallMs} realtimeMultiple=${it.realtimeMultiple} heapUsedBytes=${it.heapUsedBytes}",
      )
    }
    println("[$tag] windows=${windows.size}")
    windows.forEachIndexed { idx, w ->
      println("[$tag]   window=$idx startMs=${w.startMs} rms=${w.rms()} peak=${w.peakAbs} nonFinite=${w.nonFiniteCount} samples=${w.sampleCount}")
    }

    if (runtimeExceptionCaught != null) {
      throw AssertionError("Full-night run failed -- see printed evidence above", runtimeExceptionCaught)
    }

    // Core assertions -- see the report for full narrative detail.
    assertEquals(0L, nonFiniteTotal)
    assertEquals(13, timeline.stages.size)
    assertTrue("expected >= 9 stage transitions (13 authored, throttled polling may coalesce adjacent short ones)", stageTransitions.size >= 9)
    assertEquals(1, completionCount)
    windows.forEach { w -> assertEquals("window at ${w.startMs}ms had non-finite samples", 0L, w.nonFiniteCount) }
    assertTrue("no window should be completely silent while environment/binaural should be active", windows.all { it.rms() > 0.0 || it.startMs >= expectedTotalDurationMs - windowMs })

    // Post-run contamination check: engine must reset cleanly and run a tiny
    // deterministic fixture successfully afterward.
    ProceduralAudioEngine.wallClockMs = { System.currentTimeMillis() }
    ProceduralAudioEngine.onSleepTimerElapsed = null
    ProceduralAudioEngine.checkpointSessionId = null
    ProceduralAudioEngine.reset()
    val heapAfterReset = run {
      val rt = Runtime.getRuntime()
      rt.totalMemory() - rt.freeMemory()
    }
    // Test-only GC/settle measurement, to distinguish reclaimable garbage
    // from retained state. Never call System.gc() from production code.
    System.gc()
    val heapAfterGcSettle = run {
      val rt = Runtime.getRuntime()
      rt.totalMemory() - rt.freeMemory()
    }
    println(
      "[$tag] postRunMemory heapImmediatelyAfterRunBytes=$rtMemAfter " +
        "heapAfterResetBytes=$heapAfterReset heapAfterGcSettleBytes=$heapAfterGcSettle",
    )
    val postRunResult = OfflineRenderHarness.run(
      AudioTimelineRecord().apply {
        id = "post-full-night-sanity"
        title = "Post full-night sanity"
        seed = 1.0
        stages = listOf(TimelineStageRecord().apply { id = "s"; label = "s"; durationMs = 2_000.0; config = AudioConfigRecord() })
      },
      AudioConfigRecord(),
      bufferFrames = 960,
    )
    assertEquals(0L, postRunResult.nonFiniteSampleCount)
    assertEquals(1, postRunResult.completionCount)
    println("[$tag] post-run sanity fixture: completion=${postRunResult.completionCount} nonFinite=${postRunResult.nonFiniteSampleCount} -- no contamination detected")
  }
}
